# Generated by Django 5.1.2 on 2024-10-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
